[package]
name = "intents-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
near-sdk = "5.9"
rand = "0.9"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
